query GoogleSpreadsheets($integrationAccountId: ID!, $driveId: ID) {
  googleSpreadsheets(
    integrationAccountId: $integrationAccountId
    driveId: $driveId
  ) {
    id
    name
    createdTime
    modifiedTime
  }
}
