query GoogleWorksheets($integrationAccountId: ID!, $spreadsheetId: ID!) {
  googleWorksheets(
    integrationAccountId: $integrationAccountId
    spreadsheetId: $spreadsheetId
  ) {
    sheetId
    title
    index
  }
}
